spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}
spring.datasource.username=${BANCO}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

# OMDB
omdb.api.url=https://www.omdbapi.com/
omdb.api.key=${OMDB_KEY}
spring.jpa.show-sql=true
spring.jpa.format-sql=true